"project_id" : "7"
"api_token_env" : "CROWDIN_API_KEY"
"base_path" : "."
"base_url" : "https://eresearchqut.crowdin.com"

"preserve_hierarchy": true

files: [
 {
  "source" : "/translations/locale/en/LC_MESSAGES/django.po",
  "translation" : "/translations/locale/%locale_with_underscore%/LC_MESSAGES/%original_file_name%",
  "dest" : "django.po",
 }
]
