#
dataselenium:
  extends:
    file: docker-compose-common.yml
    service: dataselenium

# runs the lettuce tests against docker-compose-teststack.yml
devlettuce:
  image: muccg/angelman-dev
  command: lettuce
  environment:
    - DBUSER=rdrfapp
    - WAIT_FOR_RUNSERVER=1
    - WAIT_FOR_DB=1
    - WAIT_FOR_MONGO=1
    - TEST_WAIT=45
    - TEST_BROWSER=chrome
    - DEBUG=0
  volumes_from:
    - dataselenium
  external_links:
    - angelman_runservertest_1:web
    - angelman_seleniumhub_1:hub
    - angelman_dbtest_1:db
    - angelman_mongotest_1:mongo

# runs the lettuce tests against docker-compose-teststack.yml
prodlettuce:
  image: muccg/angelman-dev
  command: lettuce
  environment:
    - DBUSER=rdrfapp
    - WAIT_FOR_UWSGI=1
    - WAIT_FOR_DB=1
    - WAIT_FOR_MONGO=1
    - TEST_APP_PORT=8443
    - TEST_APP_SCHEME=https
    - TEST_APP_PATH=/app/
    - TEST_WAIT=45
    - TEST_BROWSER=chrome
    - DEBUG=0
  volumes_from:
    - dataselenium
  external_links:
    - angelman_uwsgiprod_1:uwsgi
    - angelman_seleniumhub_1:hub
    - angelman_dbprod_1:db
    - angelman_mongoprod_1:mongo
