version: '2'
services:

  # note: the host aliases are to allow the prod stack to be used as a test stack

  dbprod:
    extends:
      file: docker-compose-common.yml
      service: db
    networks:
      default:
        aliases:
          - dbtest

  dbclinicalprod:
    extends:
      file: docker-compose-common.yml
      service: db
    networks:
      default:
        aliases:
          - dbclinicaltest

  cacheprod:
    extends:
      file: docker-compose-common.yml
      service: cache
    networks:
      default:
        aliases:
          - cachetest

  mongoprod:
    extends:
      file: docker-compose-common.yml
      service: mongo
    networks:
      default:
        aliases:
          - mongotest

  nginxprod:
    extends:
      file: docker-compose-common.yml
      service: nginx
    depends_on:
      - uwsgiprod
    networks:
      default:
        aliases:
         - nginxtest

  uwsgiprod:
    image: muccg/angelman:${GIT_TAG}
    command: uwsgi_local
    environment:
      - DEBUG=0
      - WAIT_FOR_DB=1
      - WAIT_FOR_CLINICAL_DB=1
      - WAIT_FOR_CACHE=1
      - WAIT_FOR_MONGO=1
      - DJANGO_FIXTURES=test
      - ALLOWED_HOSTS=*
      - CSRF_TRUSTED_ORIGINS=localhost nginxtest
      - CACHESERVER=cacheprod
      - DBSERVER=dbprod
      - CLINICAL_DBSERVER=dbclinicalprod
      - MONGOSERVER=mongoprod
      - DBUSER=rdrfapp
      - DEPLOYMENT=test
    volumes:
      - uwsgi-prod-data:/data
    depends_on:
      - dbprod
      - dbclinicalprod
      - cacheprod
      - mongoprod
    ports:
      - "8433:8433"
    networks:
      default:
        aliases:
          - uwsgitest
          - uwsgi

volumes:
  uwsgi-prod-data:
