#
dataselenium:
  image: muccg/debian8-base
  volumes:
    - .:/app
    - ./data/selenium:/data

# runs the selenium tests against the stack above
seleniumtesthost:
  image: rdrf_webselenium
  command: selenium
  environment:
    - DJANGO_SETTINGS_MODULE=rdrf.settings
    - DBUSER=rdrfapp
    - WAIT_FOR_DB=1
    - WAIT_FOR_WEB=1
    - WAIT_FOR_MONGO=1
  volumes_from:
    - dataselenium      
  external_links:
    - rdrf_dbselenium_1:db
    - rdrf_webselenium_1:web
    - rdrf_mongoselenium_1:mongo
    - rdrf_seleniumhub_1:hub
    - rdrf_reportingselenium_1:reporting
