#
dataselenium:
  extends:
    file: docker-compose-common.yml
    service: dataselenium

# runs the lettuce tests against docker-compose-teststack.yml
lettucehost:
  image: muccg/angelman-dev
  command: lettuce
  environment:
    - DBUSER=rdrfapp
    - WAIT_FOR_RUNSERVER=1
    - WAIT_FOR_DB=1
    - WAIT_FOR_MONGO=1
  volumes_from:
    - dataselenium      
  external_links:
    - angelman_runservertest_1:web
    - angelman_seleniumhub_1:hub
    - angelman_dbtest_1:db
    - angelman_mongotest_1:mongo

