version: '3.7'

volumes:
  dev_db_data:
  dev_clinicaldb_data:
  dev_reportingdb_data:

services:
  db:
    # TODO time to upgrade? (all postgres images)
    image: postgres:9.4
    env_file:
      - docker/dev/envs/postgres
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    ports:
      - "5432"

  clinicaldb:
    image: postgres:9.4
    env_file:
      - docker/dev/envs/postgres
    volumes:
      - dev_clinicaldb_data:/var/lib/postgresql/data
    ports:
      - "5432"

  reportingdb:
    image: postgres:9.4
    env_file:
      - docker/dev/envs/postgres
    volumes:
      - dev_reportingdb_data:/var/lib/postgresql/data
    ports:
      - "5432"

  cache:
    # TODO time to upgrade?
    image: memcached:1.4

  runserver:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: eresearchqut/angelman
    env_file:
      - docker/dev/envs/postgres
      - docker/dev/envs/runserver
    volumes:
      - .:/app
      - ./data/dev/:/data
    ports:
      - "8000:8000"
    depends_on:
      - db
      - clinicaldb
      - reportingdb
      - cache

  node:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile-node
    stop_signal: SIGKILL
    image: eresearchqut/angelman-node
    command: watch
    working_dir: /app/rdrf/rdrf/rdrf/frontend
    environment:
        YARN_CACHE_FOLDER: /opt/yarn_cache
    volumes:
      - .:/app
      - ./data/dev/:/data
      - ./yarn_cache:/opt/yarn_cache
