# data only container pattern
dataprod:
  image: debian:jessie
  volumes:
    - ./data/prod:/data

dbprod:
  extends:
    file: docker-compose-common.yml
    service: db

dbclinicalprod:
    extends:
    file: docker-compose-common.yml
    service: db
    networks:
      default:
        aliases:
          - dbclinicaltest

cacheprod:
  extends:
    file: docker-compose-common.yml
    service: cache

mongoprod:
  extends:
    file: docker-compose-common.yml
    service: mongo

nginxprod:
  extends:
    file: docker-compose-common.yml
    service: nginx
  links:
    - uwsgiprod:uwsgi

uwsgiprod:
  image: muccg/angelman:${GIT_TAG}
  command: uwsgi_local
  environment:
    - DBUSER=rdrfapp
    - WAIT_FOR_DB=1
    - WAIT_FOR_CACHE=1
    - WAIT_FOR_MONGO=1
    - DEPLOYMENT=test
    - ALLOWED_HOSTS=*
  volumes_from:
    - dataprod
  links:
    - dbprod:db
    - cacheprod:cache
    - mongoprod:mongo
  ports:
    - "8433:8433"
