version: '3.7'

services:
  dbtest:
    image: postgres:9.4
    env_file:
      - docker/dev/envs/postgres  # Using same db settings as dev for now
    ports:
      - "5432"

  dbclinicaltest:
    image: postgres:9.4
    env_file:
      - docker/dev/envs/postgres
    ports:
      - "5432"

  dbreportingtest:
    image: postgres:9.4
    env_file:
      - docker/dev/envs/postgres
    ports:
      - "5432"

  cachetest:
    image: memcached:1.4
